START TRANSACTION;

DROP TABLE movimentos IF EXISTS;
DROP TABLE contas IF EXISTS;

CREATE TABLE contas(
	id INTEGER GENERATED 
		BY DEFAULT AS IDENTITY
		(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	numero VARCHAR(10) NOT NULL,
	saldo NUMERIC(10, 2)  DEFAULT 0.00 NOT NULL
);

CREATE TABLE movimentos(
	id INTEGER GENERATED 
		BY DEFAULT AS IDENTITY
		(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	valor NUMERIC(10, 2) NOT NULL,
	conta_id INTEGER NOT NULL,
	CONSTRAINT conta_do_movimento FOREIGN KEY (conta_id) REFERENCES contas (id)
);

COMMIT WORK;
