START TRANSACTION;

DROP TABLE contas IF EXISTS;
DROP TABLE movimentos IF EXISTS;

CREATE TABLE contas(
	id INTEGER GENERATED 
		BY DEFAULT AS IDENTITY
		(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	numero VARCHAR(10) NOT NULL,
	saldo NUMERIC(10, 2)  DEFAULT 0.00 NOT NULL
);

CREATE TABLE movimentos(
	valor NUMERIC(10, 2) NOT NULL,
	conta_id INTEGER NOT NULL
);

COMMIT WORK;
