START TRANSACTION;

DROP TABLE contas IF EXISTS;

CREATE TABLE contas(
	id INTEGER GENERATED 
		BY DEFAULT AS IDENTITY
		(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	numero VARCHAR(10) NOT NULL
);

COMMIT WORK;
